name: Build

on:
  push:
  pull_request:

jobs:
  build-c:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Build Profiler
        run: |
          cd backend/profiler-core
          mkdir build
          cd build
          cmake ..
          make